FROM node:22-slim

WORKDIR /usr/src/app/

RUN	npm i -g @nestjs/cli

RUN apt-get update && apt install -y netcat-openbsd openssl

COPY ./src/backend/package*.json ./

RUN npm install

EXPOSE 3000

COPY ./docker/backend/entrypoint.sh /usr/src

RUN chmod +x /usr/src/entrypoint.sh

ENTRYPOINT ["../entrypoint.sh"]