FROM python:3.11-slim

WORKDIR /usr/src/app/

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Copy mock frontend files from build context
COPY ./mock-frontend /usr/src/app

EXPOSE 5173

CMD ["python3", "-m", "http.server", "5173", "--directory", "/usr/src/app"]