import { ApiProperty } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsJWT,
  IsString,
  IsNumberString,
  Length,
} from 'class-validator';

/**
 * Data transfer object for two-factor challenge authentication.
 */
export class TwoFactorAuth {
  /**
   * 6-digit numeric TOTP authentication code generated by user device.
   * @example '123456'
   */
  @ApiProperty({
    description: '6-digit numeric TOTP authentication code',
    example: '123456',
    minLength: 6,
    maxLength: 6,
  })
  @IsNotEmpty({ message: 'the two factor code cannot be empty' })
  @Length(6, 6, { message: 'The two factor code must be exactly 6 digits' })
  @IsNumberString(
    {},
    { message: 'The two factor code must contain only numbers' },
  )
  code: string;

  /**
   * Temporary JWT token received from /api/auth/signin.
   * @example 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
   */
  @ApiProperty({
    description: 'Temporary JWT token received from /api/auth/signin challenge',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  @IsNotEmpty({ message: 'the two factor tempToken cannot be empty' })
  @IsString({ message: 'The tempToken must be a string' })
  @IsJWT({ message: 'The tempToken must be a valid JWT' })
  tempToken: string;
}
