# version: '3.8'

services:
# il contex è necessario che sia ../ altrimenti il dockerfile usa come default la posizione del docker-compose e non puo andare piu indietro dalla posizione del di partenza

#------------------------------------------------------------------------------#
#                               BACKEND
  backend:
    image: backend:1.0
    build:
      context: ../
      dockerfile: ./docker/backend_docker/dockerfile
    container_name: backend-container
    volumes:
      - ../src/backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence


#------------------------------------------------------------------------------#
#                               FRONTEND
  frontend:
    image: frontend:1.0
    build:
      context: ../
      dockerfile: ./docker/frontend_docker/dockerfile
    container_name: frontend-container
    volumes:
      - ../src/frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence


#------------------------------------------------------------------------------#
#                               NGINX
  nginx:
    depends_on:
      - frontend
    image: nginx:1.0
    build:
      context: ../
      dockerfile: ./docker/nginx_docker/dockerfile
    container_name: nginx-container
    ports:
      - 8443:8443
    networks:
      - transcendence



#------------------------------------------------------------------------------#
#                               NETWORKS
networks:
  transcendence:
    driver: bridge