# version: '3.8'

services:
# il contex è necessario che sia ../ altrimenti il dockerfile usa come default 
# la posizione del docker-compose e non puo andare piu indietro dalla posizione
# del di partenza.                                                    Luis
# Ma e' un problema di sicurezza. Lo risolvero' poi!                  Dario

#------------------------------------------------------------------------------#
#                               DATABASE
  database:
    image: database:1.0
    build:
#      context: ../
      context: ./database/
#      dockerfile: ./docker/database/dockerfile
    container_name: database-container
    ports:
      - 5432:5432 # TODO: da togliere in consegna, serve solo per testare le API
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence

#------------------------------------------------------------------------------#
#                               BACKEND
  backend:
    depends_on:
      - database
    image: backend:1.0
    build:
      context: ../
      dockerfile: ./docker/backend/dockerfile
    container_name: backend-container
#    ports:
#     - 3000:3000  TODO: da togliere in consegna, serve solo per testare le API
    env_file:
      - .env
    volumes:
      - ../src/backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence


#------------------------------------------------------------------------------#
#                               FRONTEND
  frontend:
    depends_on:
      - backend
    image: frontend:1.0
    build:
      context: ../
      dockerfile: ./docker/frontend/dockerfile
    container_name: frontend-container
    volumes:
      - ../src/frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence

  # -------------------------------------------------------------------------- #
  # Nginx web server (reverse proxy + TLS termination)
  nginx:
    # Build from local Dockerfile
    build:
      context: ./nginx/
    # Fixed container name (instead of auto-generated)
    container_name: nginx-container
    # Tag the built image (uses APP_VERSION from .env or '1.0')
    image: nginx:${APP_VERSION:-1.0}
    # Never pull from registry; always use local build
    pull_policy: never
    # Give nginx 10s to shut down gracefully (not really needed, added
    #   only for consistency between different services)
    stop_grace_period: 10s
    # Load environment variables from .env file
    env_file:
      - path: .env
        required: true
    # Non-sensitive environment variables defaults used when missing in .env.
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      NGINX_PORT: "${NGINX_PORT:-443}"
    # Expose HTTPS to host. Ports in docker compose are written in the form
    #   HOST_PORT:CONTAINER_PORT
    ports:
      - "${NGINX_PORT}:443"
    # Connect to custom bridge network
    networks:
      - transcendence
    # Start only after frontend is running and healthy
    depends_on:
      frontend:
        condition: service_started # to be changed with service_healthy
    # Auto-restart on crash or system reboot. Do not restart if manually stopped
    restart: unless-stopped

#------------------------------------------------------------------------------#
#                               NETWORKS
networks:
  transcendence:
    driver: bridge

#------------------------------------------------------------------------------#
#                               VOLUMES
volumes:
  db_data: