FROM node:22-slim

WORKDIR /usr/src/app/

# RUN	npm i -g @nestjs/cli

COPY ../../src/frontend/package*.json ./

RUN npm install vite

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]