FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx_docker/nginx.conf /etc/nginx/conf.d/

RUN apk add --no-cache openssl

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
  -keyout /etc/nginx/ssl/transcendence.key \
  -out /etc/nginx/ssl/transcendence.crt \
  -subj "/C=IT/ST=Italy/L=Italy/O=Dev/CN=localhost" \
  -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"

# COPY ssl/transcendence.crt /etc/nginx/ssl/transcendence.crt
# COPY ssl/transcendence.key /etc/nginx/ssl/transcendence.key

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]