error_log /var/log/nginx/error.log crit;
## silenzia i log del container ngnix la linea sopra, ma non tutti 
server{
	listen 443 ssl;
	server_name localhost;

 		ssl_certificate /etc/nginx/ssl/transcendence.crt;
      	ssl_certificate_key /etc/nginx/ssl/transcendence.key;
       	ssl_protocols TLSv1.3;  

	location / {
		proxy_pass http://frontend:5173;

	}
}


